<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <!-- Nuget package versions -->
    <SpectreConsoleVersion>0.49.1</SpectreConsoleVersion>
  </PropertyGroup>
  <!-- App dependencies -->
  <ItemGroup>
    <PackageVersion Include="Spectre.Console" Version="$(SpectreConsoleVersion)"/>
  </ItemGroup>
  <!-- Test dependencies -->
  <!-- SourceLink support for all Akka.NET projects -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0"/>
  </ItemGroup>
</Project>