// Copyright (c) Petabridge, LLC. All rights reserved.
// Licensed under the Apache 2.0 license. See LICENSE file in the project root for full license information.

using System.Text;
using Termina.Diagnostics;

namespace Termina.Input;

/// <summary>
/// Parses escape sequences from individual <see cref="ConsoleKeyInfo"/> values arriving from
/// the active <see cref="Platform.IPlatformConsole"/>.
/// </summary>
/// <remarks>
/// <para>
/// Whether the bytes come from <c>Console.ReadKey</c> (Windows / fallback) or from raw stdin
/// reads via <see cref="Platform.UnixConsole"/>, each byte of an escape sequence arrives as a
/// separate <see cref="ConsoleKeyInfo"/>. This parser buffers them and detects:
/// </para>
/// <list type="bullet">
///   <item><description>Bracketed paste: <c>ESC[200~</c>…content…<c>ESC[201~</c> → <see cref="PasteEvent"/></description></item>
///   <item><description>SGR mouse scroll up: <c>ESC[&lt;64;x;yM</c> → <see cref="MouseScrollEvent"/>(<c>+1</c>)</description></item>
///   <item><description>SGR mouse scroll down: <c>ESC[&lt;65;x;yM</c> → <see cref="MouseScrollEvent"/>(<c>-1</c>)</description></item>
///   <item><description>Other SGR mouse events (clicks, releases): silently consumed — prevents spurious <c>ESC</c> keypresses.</description></item>
///   <item><description>CSI u (kitty keyboard protocol): <c>ESC[keycode;modifiersu</c> → <see cref="KeyPressed"/> with correct modifiers.</description></item>
///   <item><description>Legacy CSI tilde keys: <c>ESC[5~</c> / <c>ESC[5;5~</c> → <see cref="KeyPressed"/> (PgUp/PgDn/etc. with modifiers).</description></item>
///   <item><description>CSI arrow under xterm alternate-scroll mode: <c>ESC[A</c> / <c>ESC[B</c> → <see cref="MouseScrollEvent"/>.</description></item>
///   <item><description>SS3 arrow / function key: <c>ESC O A/B/C/D/H/F/P-S</c> → <see cref="KeyPressed"/> (arrows, Home/End, F1-F4).</description></item>
///   <item><description>Alt+Enter: <c>ESC</c> followed by <c>\r</c>/<c>\n</c> → <see cref="KeyPressed"/> with Alt modifier set.</description></item>
///   <item><description>Standalone <c>ESC</c>: emitted as <see cref="KeyPressed"/> after a 50 ms timeout with no follow-up character.</description></item>
/// </list>
/// <para>
/// CSI u sequences are generated by terminals that support the kitty keyboard protocol
/// (see <see href="https://sw.kovidgoyal.net/kitty/keyboard-protocol/"/>).
/// Standard terminals cannot distinguish Ctrl+Enter from Enter because both produce
/// the same byte (0x0D); the kitty protocol solves this by sending structured escape
/// sequences instead of raw bytes
/// (see <see href="https://blog.fsck.com/releases/2026/02/26/terminal-keyboard-protocol/"/>).
/// </para>
/// <para>
/// Call <see cref="Process"/> for each key received. When <see cref="IsBufferingEscape"/> is
/// <c>true</c>, the caller should use a short read timeout (≈50 ms) and call
/// <see cref="CheckEscapeTimeout"/> when no key arrives in time.
/// </para>
/// </remarks>
internal sealed class EscapeSequenceParser
{
    private enum State { Normal, AfterEscape, InBracketSequence, InSs3Sequence, PasteBuffering }

    private State _state = State.Normal;
    private readonly StringBuilder _seqBuffer = new();
    private readonly BracketedPasteDecoder _pasteDecoder = new();
    private TerminalModeContext _modeContext = TerminalModeContext.Default;
    private long _escapeReceivedAt;

    // Injected clock for testing; defaults to Environment.TickCount64
    private readonly Func<long> _getTick;

    /// <summary>
    /// When <c>true</c>, the parser interprets bare <c>CSI A/B/C/D/H/F/P-S</c> (no params) as
    /// keyboard arrow / function keys instead of <see cref="MouseScrollEvent"/>. Set this when
    /// the kitty keyboard progressive enhancement <c>report_all_keys</c> (flag 8) is active —
    /// in that mode plain arrows are reported as canonical kitty escape codes and the only
    /// remaining source of bare <c>CSI A/B</c> is the <c>?1007h</c> alternate-scroll wheel.
    /// </summary>
    /// <remarks>
    /// When the kitty keyboard protocol is active <em>and</em> <c>?1007h</c> is also enabled,
    /// the only way to distinguish wheel-up from Up-arrow is for the parser to know which mode
    /// the terminal is in. The terminal's keyboard events get the kitty CSI-u / second-form
    /// shape; wheel events keep emitting the legacy <c>ESC OA/B</c> (DECCKM on) or
    /// <c>ESC [A/B</c> (DECCKM off) shape. With this flag set the parser routes the
    /// bare-CSI-arrow shape to <see cref="KeyPressed"/> (treating any matching SS3 as the wheel
    /// path instead — handled in <see cref="State.InSs3Sequence"/>).
    /// </remarks>
    public bool KittyReportAllKeysVisible
    {
        get => _modeContext.KittyReportAllKeysVisible;
        set => _modeContext = _modeContext with { KittyReportAllKeysVisible = value };
    }

    /// <summary>
    /// Creates a parser using the system clock.
    /// </summary>
    public EscapeSequenceParser() : this(null) { }

    /// <summary>
    /// Creates a parser with an injectable clock function.
    /// Pass a custom <paramref name="getTick"/> for deterministic unit tests.
    /// </summary>
    /// <param name="getTick">Returns the current tick in milliseconds. If null, uses <see cref="Environment.TickCount64"/>.</param>
    internal EscapeSequenceParser(Func<long>? getTick)
    {
        _getTick = getTick ?? (() => Environment.TickCount64);
    }

    /// <summary>
    /// Whether the parser is currently buffering an incomplete escape sequence.
    /// When <c>true</c>, the caller should use a short read timeout so that a standalone
    /// <c>ESC</c> key (with no follow-up) can be flushed via <see cref="CheckEscapeTimeout"/>.
    /// </summary>
    public bool IsBufferingEscape =>
        _state == State.AfterEscape || _state == State.InBracketSequence || _state == State.InSs3Sequence;

    /// <summary>
    /// If 50 ms have elapsed since an <c>ESC</c> was buffered with no follow-up character,
    /// resets state and returns a <see cref="KeyPressed"/> for the standalone <c>ESC</c>.
    /// Returns <c>null</c> if no timeout has occurred.
    /// </summary>
    public KeyPressed? CheckEscapeTimeout()
    {
        if (_state == State.AfterEscape && _getTick() - _escapeReceivedAt > 50)
        {
            _state = State.Normal;
            return new KeyPressed(new ConsoleKeyInfo('\x1b', ConsoleKey.Escape, false, false, false));
        }
        return null;
    }

    /// <summary>
    /// Processes one key from <see cref="Console.ReadKey(bool)"/> and returns the application
    /// events that should be emitted as a result. The list may be empty (e.g., while buffering
    /// a multi-character escape sequence or silently consuming a mouse click event).
    /// </summary>
    /// <param name="key">The key to process.</param>
    /// <returns>Zero or more <see cref="IInputEvent"/> instances to emit.</returns>
    public IReadOnlyList<IInputEvent> Process(ConsoleKeyInfo key)
    {
        var results = new List<IInputEvent>(2);
        ProcessCore(key, results);
        return results;
    }

    private void ProcessCore(ConsoleKeyInfo key, List<IInputEvent> results)
    {
        TerminaTrace.Input.Trace(this, "ESP: state={0} KeyChar=0x{1:X4} Key={2}",
            _state, (int)key.KeyChar, key.Key);

        switch (_state)
        {
            case State.Normal:
                if (key.Key == ConsoleKey.Escape)
                {
                    _escapeReceivedAt = _getTick();
                    _state = State.AfterEscape;
                    TerminaTrace.Input.Debug(this, "ESP: ESC received → AfterEscape");
                }
                else
                {
                    results.Add(new KeyPressed(key));
                }
                break;

            case State.AfterEscape:
                if (key.KeyChar == '[')
                {
                    _seqBuffer.Clear();
                    _seqBuffer.Append('[');
                    _state = State.InBracketSequence;
                }
                else if (key.KeyChar == 'O')
                {
                    // SS3 introducer: ESC O <final> — used for arrow keys (and PF1-4) when
                    // the terminal is in cursor-key application mode (DECCKM, ?1h). With raw
                    // stdin input these reach us as ESC + 'O' + final byte.
                    _state = State.InSs3Sequence;
                }
                else if (key.Key == ConsoleKey.Enter || key.KeyChar == '\r' || key.KeyChar == '\n')
                {
                    // ESC + Enter = Alt+Enter (terminals send Alt as ESC prefix)
                    _state = State.Normal;
                    results.Add(new KeyPressed(
                        new ConsoleKeyInfo('\r', ConsoleKey.Enter, false, alt: true, false)));
                }
                else
                {
                    // Not a CSI sequence — flush ESC, then re-process this key as Normal
                    results.Add(new KeyPressed(new ConsoleKeyInfo('\x1b', ConsoleKey.Escape, false, false, false)));
                    _state = State.Normal;
                    ProcessCore(key, results);
                }
                break;

            case State.InBracketSequence:
                _seqBuffer.Append(key.KeyChar);
                var seq = _seqBuffer.ToString();

                // Bracketed paste start: ESC[200~
                if (BracketedPasteDecoder.IsStartSequence(seq))
                {
                    _pasteDecoder.Begin();
                    _state = State.PasteBuffering;
                    TerminaTrace.Input.Debug(this, "ESP: Paste start detected → PasteBuffering");
                    break;
                }

                // Legacy xterm/VT function-key form: ESC[<num>~ or ESC[<num>;<mods>~.
                // Keep this after bracketed paste so ESC[200~ remains the paste sentinel.
                if (key.KeyChar == '~'
                    && LegacyCsiKeyboardDecoder.TryDecode(seq, out var legacyKeyEvent)
                    && legacyKeyEvent is not null)
                {
                    TerminaTrace.Input.Debug(this, "ESP: legacy CSI tilde {0} → {1}", seq, legacyKeyEvent);
                    results.Add(legacyKeyEvent);
                    _seqBuffer.Clear();
                    _state = State.Normal;
                    break;
                }

                // CSI u (kitty keyboard protocol): ESC[keycode;modifiersu
                if (key.KeyChar == 'u' && seq.Length >= 2)
                {
                    if (KittyCsiUKeyboardDecoder.TryDecode(seq, out var csiEvent) && csiEvent is not null)
                    {
                        TerminaTrace.Input.Debug(this, "ESP: CSI u detected: {0}", seq);
                        results.Add(csiEvent);
                    }
                    _seqBuffer.Clear();
                    _state = State.Normal;
                    break;
                }

                // SGR mouse event: ESC[<button;x;yM (press) or ESC[<button;x;ym (release)
                if (seq.Length >= 2 && seq[1] == '<' && (key.KeyChar == 'M' || key.KeyChar == 'm'))
                {
                    if (SgrMouseDecoder.TryDecode(seq, out var mouseEvent) && mouseEvent is not null)
                        results.Add(mouseEvent);

                    _seqBuffer.Clear();
                    _state = State.Normal;
                    break;
                }

                // Wheel-as-CSI-arrow under xterm alternate-scroll mode (?1007h).
                // Routing of bare CSI A/B depends on whether the kitty keyboard protocol is
                // active:
                //   - Kitty inactive: bare CSI A/B is the legacy ?1007h wheel emission
                //     (because real arrows arrive as SS3 OA/B under DECCKM).
                //   - Kitty active: bare CSI A/B/C/D/H/F/P-S are the kitty canonical no-mod
                //     keyboard form; wheel still emits the DECCKM-controlled SS3 form, so the
                //     CSI form is unambiguously a real key.
                if (seq.Length == 2 && CsiFunctionalDecoder.IsFunctionalFinal(key.KeyChar))
                {
                    if (CsiFunctionalDecoder.TryDecodeBareFinal(
                            key.KeyChar,
                            _modeContext,
                            out var functionalEvent)
                        && functionalEvent is not null)
                        results.Add(functionalEvent);

                    _seqBuffer.Clear();
                    _state = State.Normal;
                    break;
                }

                // Kitty "second form" with parameters: CSI 1;<mods>[:<event>] [ABCDEFHPQRS]
                // Real arrows / function keys with a modifier pressed when kitty's
                // disambiguate (bit 1) or report_all_keys (bit 8) flag is set.
                if (CsiFunctionalDecoder.IsFunctionalFinal(key.KeyChar) && seq.Length >= 3 && seq[1] != '<')
                {
                    if (KittySecondFormKeyboardDecoder.TryDecode(seq, out var keyEvent) && keyEvent is not null)
                    {
                        TerminaTrace.Input.Debug(this, "ESP: kitty second-form {0} → {1}", seq, keyEvent);
                        results.Add(keyEvent);
                    }
                    _seqBuffer.Clear();
                    _state = State.Normal;
                    break;
                }

                // If this sequence can no longer match any recognized pattern, flush as raw keys
                if (!UnknownSequenceFallbackDecoder.CouldLeadToRecognizedSequence(seq))
                {
                    UnknownSequenceFallbackDecoder.AppendRawKeyEvents(seq, results);
                    _seqBuffer.Clear();
                    _state = State.Normal;
                }
                break;

            case State.InSs3Sequence:
            {
                // ESC O A/B/C/D -> arrow keys delivered by the terminal under DECCKM (?1h).
                // We re-emit these as the same ConsoleKeyInfo shape Console.ReadKey used to
                // produce for arrow keys, so existing focus/scroll handlers see no difference.
                //
                // EXCEPTION: when the kitty keyboard protocol is active, real keyboard arrows
                // arrive via the kitty CSI-u / second-form path instead, so any remaining
                // SS3 OA/OB at this point must be the ?1007h wheel emission under DECCKM on.
                // (SS3 OC/OD never come from the wheel — there is no horizontal wheel.)
                if (Ss3KeyboardDecoder.TryDecode(key.KeyChar, _modeContext, out var ss3Event))
                {
                    TerminaTrace.Input.Debug(this, "ESP: SS3 O{0} → {1}", key.KeyChar, ss3Event);
                    if (ss3Event is not null)
                        results.Add(ss3Event);
                }
                else
                {
                    // Unknown SS3 sequence — flush ESC + 'O' + this char as raw keys.
                    UnknownSequenceFallbackDecoder.AppendRawSs3KeyEvents(key.KeyChar, results);
                }
                _state = State.Normal;
                break;
            }

            case State.PasteBuffering:
                if (_pasteDecoder.TryConsume(key, out var pasteEvent))
                {
                    TerminaTrace.Input.Debug(this, "ESP: Paste end detected, {0} chars", pasteEvent!.Content.Length);
                    results.Add(pasteEvent);
                    _state = State.Normal;
                }
                break;
        }
    }

}
