name: Publish NuGet

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  publish-nuget:

    name: publish-nuget
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v6.0.1
      with:
        lfs: true
        fetch-depth: 0
        
    - name: "Install .NET SDK"
      uses: actions/setup-dotnet@v5.0.1
      with:
        global-json-file: "./global.json"

    - name: "Restore .NET tools"
      run: dotnet tool restore

    - name: "Update release notes"
      shell: pwsh
      run: |
        ./build.ps1

    - name: Create Packages
      run:  dotnet pack /p:PackageVersion=${{ github.ref_name }} -c Release -o ./output

    - name: Push Packages
      run: dotnet nuget push "output/*.nupkg" -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: 'Termina ${{ github.ref_name }}'
        body_path: RELEASE_NOTES.md
        draft: false
        prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'rc') }}
        files: |
          output/*.nupkg
          output/*.snupkg